# Generated by Django 4.0.3 on 2022-05-22 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postContent', models.CharField(max_length=500)),
                ('image', models.ImageField(default='posts/images/lake.jpg', upload_to='posts/images')),
                ('video', models.FileField(blank=True, upload_to='posts/videos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='post_author')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='post_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
